#!/usr/bin/env python3
# coding: utf-8
"""
Tapoアプリの「データエクスポート」(メールで届く .xls) をDB投入用SQLに変換する。

    pip install xlrd
    python3 scripts/import_tapo_export.py --device plug1 export/*.xls > import.sql
    scp import.sql vps:~/ && ssh vps 'sudo mysql ... tapo < ~/import.sql'

アプリはタブごとに「窓の長さ」と「粒度」が固定されたシートを吐く:

    タブ  粒度    保持期間   投入先
    日    5分     約1日      power_minute
    週    1時間   約1週間    energy_hourly（kWhシートのみ。Wシートは瞬時値なので既定では捨てる）
    月    1日     約3ヶ月    energy_daily
    年    1ヶ月   約1年      energy_monthly

シートの識別はシート名ではなくヘッダの単位文字列("kWh" / "(W)")と時刻の刻み幅で行う
（シート名はロケール依存で、ファイル名も "Untitled" などになることがあるため）。

各系列の**末尾1件はエクスポート時点までの途中集計**なので、日別・月別からは除外する
（例: 08:50 にエクスポートすると当日の日別値はその時点までの積算になる）。
時間別・5分刻みは末尾も確定値なのでそのまま入れる。
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime

try:
    import xlrd
except ImportError:
    print("xlrd が必要です: pip install xlrd", file=sys.stderr)
    raise

TS_FORMATS = ("%Y/%m/%d %H:%M:%S", "%Y/%m/%d", "%Y/%m")


def parse_ts(s: str) -> tuple[datetime, str]:
    for fmt in TS_FORMATS:
        try:
            return datetime.strptime(s, fmt), fmt
        except ValueError:
            continue
    raise ValueError("時刻として解釈できません: {!r}".format(s))


def read_sheet(sheet) -> tuple[list[tuple[datetime, float]], str, str, int | None]:
    """(行, 単位文字列, 時刻フォーマット, 刻み秒) を返す"""
    unit = str(sheet.cell_value(0, 1))
    rows: list[tuple[datetime, float]] = []
    fmt = ""
    for r in range(1, sheet.nrows):
        ts, fmt = parse_ts(str(sheet.cell_value(r, 0)).strip())
        rows.append((ts, float(sheet.cell_value(r, 1))))
    step = int((rows[1][0] - rows[0][0]).total_seconds()) if len(rows) > 1 else None
    return rows, unit, fmt, step


def emit(table: str, col: str, device: str, rows: list[tuple[str, int]], label: str) -> None:
    if not rows:
        return
    print("-- {}: {} 行  {} .. {}  合計 {} Wh".format(label, len(rows), rows[0][0], rows[-1][0],
                                                     sum(w for _, w in rows)))
    print("INSERT INTO {} (device_key, `{}`, wh, source) VALUES".format(table, col))
    print(",\n".join("  ('{}', '{}', {}, 'export')".format(device, k, w) for k, w in rows))
    print("ON DUPLICATE KEY UPDATE wh = VALUES(wh), source = VALUES(source);")
    print()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", required=True, help="device_key (例: plug1)")
    ap.add_argument("--include-hourly-power", action="store_true",
                    help="1時間刻みの瞬時電力(W)も power_minute に入れる（既定では捨てる）")
    ap.add_argument("files", nargs="+", help="エクスポートされた .xls ファイル")
    args = ap.parse_args()
    dev = args.device

    print("-- generated by scripts/import_tapo_export.py at {:%Y-%m-%d %H:%M:%S}".format(datetime.now()))
    print("-- device_key = {}".format(dev))
    print()

    for path in args.files:
        for sheet in xlrd.open_workbook(path).sheets():
            if sheet.nrows < 2:
                continue
            rows, unit, fmt, step = read_sheet(sheet)
            is_energy = "kWh" in unit

            if is_energy and step == 3600:
                print("-- energy_hourly: {} 行  {} .. {}".format(len(rows), rows[0][0], rows[-1][0]))
                print("INSERT INTO energy_hourly (device_key, hour_start, wh) VALUES")
                print(",\n".join("  ('{}', '{:%Y-%m-%d %H:%M:%S}', {})".format(dev, t, round(v * 1000))
                                 for t, v in rows))
                print("ON DUPLICATE KEY UPDATE wh = VALUES(wh);")
                print()
            elif is_energy and fmt == "%Y/%m/%d":
                # 末尾はエクスポート時点までの途中集計なので落とす
                emit("energy_daily", "day", dev,
                     [(t.strftime("%Y-%m-%d"), round(v * 1000)) for t, v in rows[:-1]],
                     "energy_daily (末尾1日は途中集計のため除外)")
            elif is_energy and fmt == "%Y/%m":
                emit("energy_monthly", "month", dev,
                     [(t.strftime("%Y-%m-01"), round(v * 1000)) for t, v in rows[:-1]],
                     "energy_monthly (末尾1ヶ月は途中集計のため除外)")
            elif not is_energy and (step == 300 or args.include_hourly_power):
                print("-- power_minute: {} 行  {} .. {}  (刻み {}秒)".format(
                    len(rows), rows[0][0], rows[-1][0], step))
                print("INSERT INTO power_minute (device_key, ts, power_w) VALUES")
                print(",\n".join("  ('{}', '{:%Y-%m-%d %H:%M:%S}', {:.1f})".format(dev, t, v)
                                 for t, v in rows))
                print("ON DUPLICATE KEY UPDATE power_w = VALUES(power_w);")
                print()
            else:
                print("-- skip: unit={!r} step={} fmt={} rows={}".format(unit, step, fmt, len(rows)))
                print()


if __name__ == "__main__":
    main()
